blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url:https://github.com/o-ga09/o-ga09/issues/new?template=custom.md&projects=o-ga09%2FToDo%2F1&labels=ToDo
